### ISSUE TITLE
New Google Doc URLs

### ISSUE THREAD

**Issue by billsinc** [avand/brioche#1]
As you might know, the new Doc URLs do not contain a "key" and won't work with this.  What do you think it would take to update this to reflect their new URL structure?

**Comment by avand** [comment]
Well, we're using the (Google Drive gem)[gimite/google-drive-ruby] at version `0.3.0`. We probably want to upgrade to `0.3.6`. But glancing at the commit history, that may not fix the problem. Feel free to fork and submit a pull request once you get it working. I'm not actively maintaining this project anymore.

**Comment by billsinc** [comment]
I was mistaken...the key still applies to spreadsheets but not forms...I'm testing it now.  Thanks.

**Comment by avand** [comment]
No problem!
